### ISSUE TITLE
All nodes broken if inputs converted to widgets

### ISSUE THREAD

**Issue by stevehooker** [crystian/ComfyUI-Crystools#10]
If I convert an input to a widget, save the workflow, then reopen, the input is returned, as well as the widget. That is, I get both. This happens on all such modified nodes. Text inputs, Ksamplers, and here in this screen shot,  a prompt.

I have 'fix node (recreate) losing all my structure, values, colours, inputs and widgets and then remade them. But, saving the workflow and reopening it, and everything is doubled once more. To be clear no harm is done when running the workflow, it just looks bad, but does not break anything, it doesn't use the 'ghost' values. Further, it was happening in all workflows that I opened, whether I was using one of your custom nodes within that workflow, or not, so long as I had converted a widget to an input. Deleting your nodes and my problem has gone away.

More here:
https://www.reddit.com/r/comfyui/comments/192dkbt/help_needed_i_get_reapeted_values_on_some_nodes/

<img width="603" alt="Screenshot 2024-01-09 193200" src="https://github.com/crystian/ComfyUI-Crystools/assets/27295830/33acb438-ee8e-4fc1-ada8-ff3dafe4c30f">

**Comment by crystian** [comment]
Oh, thanks! I'll check now! may with the update of confyUI broken some stuff, let me check right now!

**Comment by crystian** [comment]
Can you test please? update both extensions, crystools and crystools-save, thanks!
