### ISSUE TITLE
[Crystools INFO] GPU/s: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte

### ISSUE THREAD

**Issue by Enchante503** [crystian/ComfyUI-Crystools#102]
**Describe the bug**  
[Crystools INFO] GPU/s:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte

**Comment by crystian** [comment]
I need more info, please, fill the form
