### ISSUE TITLE
Link between VAE Encode for impainting and SamplerCustomAdvanced does stops confyui from executing when there is a latent space switch (under certain conditions)

### ISSUE THREAD

**Issue by mcDandy** [crystian/ComfyUI-Crystools#103]
**Describe the bug**  
When you have two latent space switches AND first one in chain has true at imput AND there exists a link between VAE Encode for impaint and SamplerCustomAdvanced  Comfyui will imidietly finish processing.

**To Reproduce**  
__Please attach a workflow file to make it easier for others to reproduce the error!__

[workflow_err.json](https://github.com/user-attachments/files/16488607/workflow_err.json)
Switch the second input named "false = i2i; true = impaint" to true to experience the bug. FLUX dev or FLUX schnell is needed. Cannot even save it when it is set to true (when the bug is active)

**Expected behavior**  

Image getting impainted

**Screenshots**  
![image](https://github.com/user-attachments/assets/0d94543a-0c59-4a13-b145-d48cabdeb941)
Clicking Queue prompt and absolutly nothing is happening.

**Error in console:**  
If applicable, add the error message from the console.

**Versions:**  
Copy the output of the console (4 parts), like this:
```
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]```
```
Total VRAM 12282 MB, total RAM 32468 MB
pytorch version: 2.1.2+cu121
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 Laptop GPU : cudaMallocAsync
```
```
[Crystools INFO] Crystools version: 1.16.6
[Crystools INFO] CPU: 13th Gen Intel(R) Core(TM) i9-13950HX - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4080 Laptop GPU
[Crystools INFO] NVIDIA Driver: 560.70
```
```
### ComfyUI Revision: 2464 [0a6b0081] | Released on '2024-08-04'
```

**Additional context**  
Add any other context about the problem here.
Model I am using in this workflow: https://huggingface.co/black-forest-labs

**Comment by crystian** [comment]
your workflow is strange, please be more clear with a new workflow, thanks
