### ISSUE TITLE
Crystaltools not visible and doesn't throw any error in runpod.

### ISSUE THREAD

**Issue by mogupta** [crystian/ComfyUI-Crystools#104]
**Describe the bug**  
Crystaltools not visible and doesn't throw any error in runpod.

**To Reproduce**  
Just use runpod to install comfyui . 
1. Tried installing using comfy ui manager
2. Tried installing using git v1.16.6

**Expected behavior**  
Nothing is visible on the right window as it should

**Screenshots**  
![image](https://github.com/user-attachments/assets/59bf3b90-ab71-4397-ba26-7e1910329aa2)
![image](https://github.com/user-attachments/assets/05c53314-6791-4b42-83ec-c1be2a634e2b)

**Error in console:**  
no errors

**Versions:**  
Copy the output of the console (4 parts), like this:
```
** Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
```
```

```
```
[Crystools INFO]  no logs
```
```
2024-08-05T23:18:20.941406165Z ### Loading: ComfyUI-Manager (V2.48.5)
2024-08-05T23:18:20.941410649Z ### ComfyUI Revision: 2129 [719fb2c8] *DETACHED | Released on '2024-04-14'
```

**Additional context**

**Comment by JamesIV4** [comment]
Same issue here, except running locally on Windows. Installed using Comfy UI Manager.

ComfyUI: 2489[8115d8](2024-08-07)
Manager: V2.48.5

**Comment by MethodJiao** [comment]
Did you use nginx secondary directory?

**Comment by MethodJiao** [comment]
You may be able to F12 to check the crystools related requests and see if they are successful.

**Comment by mogupta** [comment]
Fresh comfyui install fixed the issue for me.

**Comment by JamesIV4** [comment]
I haven't had this issue resolved yet. In the console, I see this:
```
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 2.6, "ram_total": 17114193920, "ram_used": 16388325376, "ram_used_percent": 95.8, "hdd_total": 250055688192, "hdd_used": 204988538880, "hdd_used_percent": 82.0, "device_type": "cuda", "gpus": [{"gpu_utilization": 16, "gpu_temperature": 49, "vram_total": 12884901888, "vram_used": 7991558144, "vram_used_percent": 62.02265421549479}]}} Error: Unknown message type crystools.monitor
```

**Comment by JamesIV4** [comment]
It's working fine if I launch ComfyUI seperately from SwarmUI. I'll just delete SwarmUI, I don't use any of its features.

**Comment by crystian** [comment]
I'm not support SwarmUI, just comfyUI, sorry :(

**Comment by arunhk3** [comment]
Idea is to not install ComfyUI backend when setting up:

1) Install ComfyUI using a Conda Env (skip this if ComfyUI is already installed)
2) Install dependencies/requirements (skip this if ComfyUI is already installed)
3) The install SwarmUI with no backend
4) Open SwarmUI and go to Servers --> Backends
5) Click on 'ComfyUI Self-Starting' button
6) Add the path to ComfyUI's main.py using full path
      Example: python C:/ComfyUI/main.py
7) Add arguments (if necessary)

Create a script to activate conda environment before which should also launch SwarmUI. Works like a charm!
