### ISSUE TITLE
Request split the view into 2-columns for the new ComfyUI interface?

### ISSUE THREAD

**Issue by ricperry** [crystian/ComfyUI-Crystools#105]
![image](https://github.com/user-attachments/assets/73a9e16e-b938-4c54-833e-320fd31f29af)

Lots of wasted screen realestate with the new layout. I recognize this isn't official yet, so the urgency in changing it isn't immediate or anything. Just getting ahead of this.

**Comment by crystian** [comment]
this weekend I'll do ;)

**Comment by kakachiex2** [comment]
Something like chainner UI
![Screenshot 2024-08-16 121545](https://github.com/user-attachments/assets/7f8dedc0-21c8-4fdf-8fa7-03c822ff4ea0)

**Comment by wibur0620** [comment]
> Something like chainner UI ![Screenshot 2024-08-16 121545](https://private-user-images.githubusercontent.com/1762112/358646596-7f8dedc0-21c8-4fdf-8fa7-03c822ff4ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzY1MDQsIm5iZiI6MTcyNDM3NjIwNCwicGF0aCI6Ii8xNzYyMTEyLzM1ODY0NjU5Ni03ZjhkZWRjMC0yMWM4LTRmZGYtOGZhNy0wM2M4MjJmZjRlYTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDEyMzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDFkZDAxZWRhOWU3NjMzNWRiMzMwNGYzMTQ5ZGVmZDJiNmU0NDBlNWUyYjQzYTJkMDM2NjNhYmZkZjE1ODQyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Gm5Slyy288P8uErVZSVTuWFmL3HmYeQPC22D1JqznrA)

Support this.

**Comment by gonzalu** [comment]
Any updates on this? It did work well for some time and then something broke it on new UI. 

Thank you.

**Comment by crystian** [comment]
I'm working on it :)

**Comment by crystian** [comment]
same issue: https://github.com/crystian/ComfyUI-Crystools/issues/71
