### ISSUE TITLE
Export that great node !

### ISSUE THREAD

**Issue by tetsuoo-online** [crystian/ComfyUI-Crystools#107]
**Is your feature request related to a problem? Please describe.**
My problem is that I'm only interested in 1 node lol

**Describe the solution you'd like**
I'd like to install the Get Resolution node nothing else

**Describe alternatives you've considered**
I considered asking Claude or chatGPT how to do it, actually I did and it almost worked... I was so close x)
What did I miss ? Can you help please I tried but I think it's best to ask to a real coder !

**Additional context**
But I failed
![image](https://github.com/user-attachments/assets/dad7ee27-6de4-4e60-a701-2d8db2fa5df6)
[crystools_get_image_resolution.zip](https://github.com/user-attachments/files/16651002/crystools_get_image_resolution.zip)

**Comment by crystian** [comment]
this has two parts, python and web you need to make changes on both :)

**Comment by tetsuoo-online** [comment]
> this has two parts, python and web you need to make changes on both :)

Do you mean... I will have to deal with Javascript stuff ? Oh no~~ haha okay thank you very much ^^
I'm guessing that's the part responsible for displaying or refreshing nodes, I tried to make a custom node before (completely different thing, not related to crystools) and I failed to implement the web... Now I know I need to investigate more.
