### ISSUE TITLE
Would it be possible to make a "node" that displays the live progress-bar-info (see image in this post)

### ISSUE THREAD

**Issue by AlexData-Hawkhill** [crystian/ComfyUI-Crystools#108]
**Is your feature request related to a problem? Please describe:**
The lack of a node that can display the progress bars, as some might find it more handy to put it directly in the project, and hide it from the menu.

**Describe the solution you'd like:**
Would it be possible to make a "node" that displays the same live progress-bar-info that we can see in the old ComfyUI menu?
So that we could just add it as a node in the project, and display the same live-updated progress-bars inside a node? 
Is that even possible?

**Describe alternatives you've considered:**
Alternatives are already planned I see when I read the current open issues, and the alternative is in the new top/bottom menu. This idea would however extend **_beyond_** that menu, and for some it might have additional usefulness.

**Additional context:**
I've made a screenshot of the idea I have in mind!
![CanThisBeDone](https://github.com/user-attachments/assets/051c0763-dce6-4e39-8904-63156f52bb1d)

**Comment by crystian** [comment]
sounds good @AlexData-Hawkhill But, I don't have time :(

**Comment by crystian** [comment]
next release will be included on horizontal bar
