### ISSUE TITLE
Crystool failing to install on Colab!

### ISSUE THREAD

**Issue by eXWoLL** [crystian/ComfyUI-Crystools#109]
I'm getting the following error on colab:

`[Crystools INFO] Crystools version: 1.16.6
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Crystools/__init__.py", line 18, in <module>
    from .nodes.image import CImagePreviewFromImage, CImageLoadWithMetadata, CImageGetResolution, CImagePreviewFromMetadata, \
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Crystools/nodes/image.py", line 12, in <module>
    from PIL.ExifTags import TAGS, GPSTAGS, IFD
ImportError: cannot import name 'IFD' from 'PIL.ExifTags' (/usr/local/lib/python3.10/dist-packages/PIL/ExifTags.py)

Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Crystools module for custom nodes: cannot import name 'IFD' from 'PIL.ExifTags' (/usr/local/lib/python3.10/dist-packages/PIL/ExifTags.py)
`
Tried updating and reinstalling, also all requirements from the .txt are installed! keep getting the same thing :/

**Comment by festivus37** [comment]
I'm getting the same thing and can't seem to resolve it.

**Comment by festivus37** [comment]
Ok, this fixed it for me. 
pip install pillow==9.5.0

**Comment by eXWoLL** [comment]
> Ok, this fixed it for me. pip install pillow==9.5.0

Did something similar: 
Added these lines after the "update comfy" and "install dependencies":

> !pip3 install -r requirements.txt
!pip3 pip install --upgrade pip
!pip3 pip install --upgrade Pillow

**Comment by crystian** [comment]
> > Ok, this fixed it for me. pip install pillow==9.5.0
> 
> Did something similar: Added these lines after the "update comfy" and "install dependencies":
> 
> > !pip3 install -r requirements.txt
> > !pip3 pip install --upgrade pip
> > !pip3 pip install --upgrade Pillow

@eXWoLL did you try it?

**Comment by jnaviask** [comment]
Changing pillow's version in the crystools install directory did nothing. Am I supposed to run the upgrade / version peg elsewhere?

**Comment by crystian** [comment]
try again (with a new install)
1.18.2
