### ISSUE TITLE
Resources monitor items horizontal

### ISSUE THREAD

**Issue by pandayummy** [crystian/ComfyUI-Crystools#110]
![image](https://github.com/user-attachments/assets/b660f97d-cbbd-426a-a6ce-f92d9f55b7e3)

It would be better to make them display horizontally on new UI

like this:
![image](https://github.com/user-attachments/assets/e905a940-2aa3-4538-8cf5-8c17d3504fa7)

**Comment by amimi818** [comment]
Want the same...

**Comment by AlexD81** [comment]
the same for me, nothing is shown anymore

**Comment by gonzalu** [comment]
It did work for a few releases post new UI ...

**Comment by AlexD81** [comment]
for me it's still not visible.  I've reinstalled addon a couple times. Don't know. Nothing is visible

**Comment by gonzalu** [comment]
> for me it's still not visible. I've reinstalled addon a couple times. Don't know. Nothing is visible

same :( 

However, I saw a video from Sebastian Kampf he did a day ago and his is working...

**Comment by derspanier1** [comment]
not working for me either. sad noises

**Comment by jwvanderbeck** [comment]
I don't even see it in the settings at all

**Comment by chnisar515** [comment]
i am facing the same issue when i activate new menu then the resources monitor not showing but when i disable new menu it showing me well. My ComfyUI and all nodes are fully updated.

![Screenshot 2024-09-03 154106](https://github.com/user-attachments/assets/bc71da8f-16f9-4cfa-9c54-daf3c3ff1b84)

**Comment by crystian** [comment]
I'm working on it: https://github.com/crystian/ComfyUI-Crystools/issues/71
