### ISSUE TITLE
Fails to import on loading ComfyUI with new session on COLAB

### ISSUE THREAD

**Issue by DMHolman** [crystian/ComfyUI-Crystools#112]
**Describe the bug**  
Installing Crystools, there is no problem.  It runs perfectly.  Refresh or Restart in ComfyUI and again, no problems.  The problem is, once the session on COLAB ends and I come back later, Crystools fails to import in the new session on ComfyUI start (traceback follows).  The only way I can fix this is to uninstall Crystools, RESTART from ComfyUI manager, install Crystools and then RESTART one more time.  Then it is fine again until I end the current session and come back later at which point I have to do the uninstall/install all over again.  Trying to understand if this is a Crystools issue or a Python issue.

**Error in console:**  
Traceback (most recent call last):
  File "/content/drive/MyDrive/AI/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Crystools/__init__.py", line 10, in <module>
    from .core import version, logger
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Crystools/core/__init__.py", line 5, in <module>
    from .common import *
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Crystools/core/common.py", line 4, in <module>
    from deepdiff import DeepDiff
ModuleNotFoundError: No module named 'deepdiff'

Cannot import /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Crystools module for custom nodes: No module named 'deepdiff'

**Versions:**  
Python version: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]

Total VRAM 40514 MB, total RAM 85480 MB
Set vram state to: NORMAL_VRAM

Device: cuda:0 NVIDIA A100-SXM4-40GB : cudaMallocAsync
```
```
[Crystools INFO] Crystools version: 1.16.6
[Crystools INFO] CPU: Intel(R) Xeon(R) CPU @ 2.20GHz - Arch: x86_64 - OS: Linux 6.1.85+
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA A100-SXM4-40GB
[Crystools INFO] NVIDIA Driver: 535.104.05
```
```
### ComfyUI Revision: 2620 [ab130001] | Released on '2024-08-27'
```

**Comment by crystian** [comment]
follow this: https://github.com/crystian/ComfyUI-Crystools/issues/109
