### ISSUE TITLE
Resource monitor doesn't work when running Comfy on a subpath

### ISSUE THREAD

**Issue by Rafaeltheraven** [crystian/ComfyUI-Crystools#114]
**Describe the bug**  
Crystools tries to make requests to `/scripts/app.js`, `/scripts/api.js` and `/scripts/widgets.js`. Because of the leading `/`, it's trying to get these from the root, but I am running ComfyUI on the `/comfy/` subpath, causing the requests to 404 and the plugin to fail loading.

**To Reproduce**  
Run ComyUI on a subpath. Install crystools.

**Expected behavior**  
Request from the proper `/comfy/scripts/` path (or whatever anyone's subpath may be).

**Additional context**  
Relevant Nginx config looks as follows:

```
location /comfy/ {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        #Websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;

        proxy_pass http://localhost:{PORT}/;
}
```

**Comment by crystian** [comment]
I tired it in the pass, I'll try now with lots of changes from comfy

**Comment by crystian** [comment]
Try again please @Rafaeltheraven

**Comment by crystian** [comment]
try again and reopone the issue if it does not work, thanks

**Comment by Rafaeltheraven** [comment]
Hey there, sorry for not responding, I kinda fell off genning for a while and forgot.

Just tried out your fix, it mostly works! Only issues is that `/extensions/ComfyUI-Crystools/monitor.css` is still being retrieved from the root instead of the subpath, so it looks kinda borked, but the data is all there.
