### ISSUE TITLE
ive never gotten crystools to work on PC, only mac

### ISSUE THREAD

**Issue by rachelcenter** [crystian/ComfyUI-Crystools#115]
**Describe the bug**  
i followed your instructions for repo and consistently get error regarding requirements

**To Reproduce**  
follow AMD install instructions on github page

**Expected behavior**  
I expect to not get errors in the console

**Screenshots**  

**Error in console:**  
D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools>pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://test.pypi.org/simple
Collecting deepdiff (from -r requirements.txt (line 1))
  Using cached deepdiff-8.0.1-py3-none-any.whl.metadata (8.5 kB)
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools>
**Versions:**  
Copy the output of the console (4 parts), like this:
```
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
```
```
Total VRAM 12287 MB, total RAM 130996 MB
Set vram state to: NORMAL_VRAM
```
```
[Crystools INFO] Crystools version: 1.9.2
[Crystools INFO] CPU: AMD Ryzen 9 5950X 16-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3080 Ti
[Crystools INFO] NVIDIA Driver: 546.33
```
```
### Loading: ComfyUI-Manager (V1.25.3)
### ComfyUI Revision: 1886 [6a10640f] | Released on '2024-01-08'
```

**Additional context**  
full error log:
Microsoft Windows [Version 10.0.22631.4037]
(c) Microsoft Corporation. All rights reserved.

D:\ComfyUI_windows_portable\ComfyUI\custom_nodes>git clone -b AMD https://github.com/crystian/ComfyUI-Crystools.git
Cloning into 'ComfyUI-Crystools'...
remote: Enumerating objects: 1266, done.
remote: Counting objects: 100% (168/168), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 1266 (delta 85), reused 95 (delta 74), pack-reused 1098 (from 1)
Receiving objects: 100% (1266/1266), 15.14 MiB | 19.52 MiB/s, done.
Resolving deltas: 100% (759/759), done.

D:\ComfyUI_windows_portable\ComfyUI\custom_nodes>cd ComfyUI-Crystools

D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools>pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://test.pypi.org/simple
Collecting deepdiff (from -r requirements.txt (line 1))
  Using cached deepdiff-8.0.1-py3-none-any.whl.metadata (8.5 kB)
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools>python.exe -m pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\program files (x86)\python311-32\lib\site-packages (24.0)
Collecting pip
  Using cached pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.2-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  WARNING: The scripts pip.exe, pip3.11.exe and pip3.exe are installed in 'C:\Users\rache\AppData\Roaming\Python\Python311-32\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-24.2

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools>pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://test.pypi.org/simple
Collecting deepdiff (from -r requirements.txt (line 1))
  Using cached deepdiff-8.0.1-py3-none-any.whl.metadata (8.5 kB)
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools>

**Comment by jnaviask** [comment]
I'm also getting issues with deepdiff. Install output:
```
Requirement already satisfied: deepdiff in c:\users\jake\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 1)) (8.0.1)
```

Output when running ComfyUI (up to date incl all dependencies as of today):

```
Traceback (most recent call last):
  File "C:\Users\Jake\Documents\ai\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Jake\Documents\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\__init__.py", line 10, in <module>
    from .core import version, logger
  File "C:\Users\Jake\Documents\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\core\__init__.py", line 5, in <module>
    from .common import *
  File "C:\Users\Jake\Documents\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\core\common.py", line 4, in <module>
    from deepdiff import DeepDiff
ModuleNotFoundError: No module named 'deepdiff'
```

Maybe it's a versioning or naming issue? Not sure why the import would fail here.

**Comment by crystian** [comment]
can you try this?
https://github.com/crystian/ComfyUI-Crystools/issues/109#issuecomment-2322986613

**Comment by jnaviask** [comment]
@crystian I tried running the pillow version peg in the crystools directory, it didn't change the output on ComfyUI's side.

**Comment by crystian** [comment]
thank you for your test, if it breaks please reopen this issue
