### ISSUE TITLE
 0.1 seconds (IMPORT FAILED): E:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Crystools

### ISSUE THREAD

**Issue by 1001celeritas** [crystian/ComfyUI-Crystools#12]
Hey, I have this issue when I run Pinokio with your nodes installed, the nodes look great and I would like to use them.

I noticed another issue the same as mine here and have updated Pillow to 10.x.x, and I still get the same error...

Cannot import E:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Crystools module for custom nodes: cannot import name 'IFD' from 'PIL.ExifTags' (E:\pinokio\api\comfyui.pinokio.git\ComfyUI\env\lib\site-packages\PIL\ExifTags.py)

I'm very new to python sorry - what information can I provide you with to help resolve this issue?

Many thanks

**Comment by tetsuoo-online** [comment]
I use Pinokio too, to be honest the only way to fix this was to delete ComfyUI completely and reinstall it from scratch :(
It's not just Crystools nor Pinokio, it happens a lot with extension, dependencies break all the time.
Reinstalling the custom nodes or even deleting the env folder wasn't enough. Sorry

**Comment by crystian** [comment]
Yes, as @tetsuoo-online said (Thanks!), is "common" to reinstall all dependencies (even with a new venv)

You can use something like my scripts for installation in less than 10 minutes.

If the issue persists, please create a new one but using the form please; I need more data.

**Comment by 1001celeritas** [comment]
cyrstian, (https://gist.github.com/crystian/1ffd2e4d97433b419bf5b0f5acf4101a)

Thanks for the link to your scripts, sadly I don't understand enough to make use of them without descriptions.

This is the only issue I have with my comfy install at the moment.

1. Is it possible to look at a .log and find the specific conflict/ fail point your nodes have?
2. Are you suggesting I could fix this issue if I update all the dependencies for comfyUI? - If so how would I go about this? 

Many thanks

**Comment by crystian** [comment]
yeap, the number 2 sure, there a lot of videos/information about that :) (reinstall python and comfyui)

**Comment by 1001celeritas** [comment]
thank you crystian, 

If I run script number 2 will it reinstall all the cusatom nodes i currently use? Or is it a wipe?
Does it matter where I run script 2 from?

Sorry for being so dumb about this stuff, your help is much appreciated.

One more thing - where is the submission form plz? (sorry once again for being such a newb.)

**Comment by 1001celeritas** [comment]
I wonder if this further information, is what you require for your work, many thanks

[2024-01-10 00:11] [Crystools [0;32mINFO[0m] Crystools version: 1.3.4
[2024-01-10 00:11] Traceback (most recent call last):
  File "E:\pinokio\api\comfyui.pinokio.git\ComfyUI\nodes.py", line 1814, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Crystools\__init__.py", line 18, in <module>
    from .nodes.image import CImagePreviewFromImage, CImageLoadWithMetadata, CImageGetResolution, CImagePreviewFromMetadata, \
  File "E:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Crystools\nodes\image.py", line 11, in <module>
    from PIL.ExifTags import TAGS, GPSTAGS, IFD
ImportError: cannot import name 'IFD' from 'PIL.ExifTags' (E:\pinokio\api\comfyui.pinokio.git\ComfyUI\env\lib\site-packages\PIL\ExifTags.py)

**Comment by crystian** [comment]
No worries, you can try to install the dependency, but maybe you can break your python environment; you can try with:

```
pip install pillow==9.5.0
```

**Comment by 1001celeritas** [comment]
Thanks, crystian - it was the first thing i tried after reading the other issue from tetsuoo, sadly this did not work for me.

Is there any information I can send you that would help?
