### ISSUE TITLE
Crystal Monitors Do Not Show on Latest ComfyUI GUI Update

### ISSUE THREAD

**Issue by camoody1** [crystian/ComfyUI-Crystools#127]
**Describe the bug**  
The latest ComfyUI GUI changes have made the Crystal Monitors disappear from the toolbar.

**To Reproduce**  

**Expected behavior**  

**Screenshots**  
![image](https://github.com/user-attachments/assets/fd400e20-8bae-49b3-8c04-aa5ad54501dc)

**Error in console:**  
N/A

**Versions:**  
Copy the output of the console (4 parts), like this:
```
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
```
```
Total VRAM 12282 MB, total RAM 65463 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
```
```
[Crystools INFO] Crystools version: 1.18.4
[Crystools INFO] CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4070 Ti
[Crystools INFO] NVIDIA Driver: 561.09
```
```
### Loading: ComfyUI-Manager (V2.51.2)
### ComfyUI Revision: 2729 [037c3159] | Released on '2024-09-25'
```

**Additional context**  
N/A

**Comment by yincangshiwei** [comment]
I also have the same problem

**Comment by crystian** [comment]
ummm, do you see the botton of queue? @camoody1 @yincangshiwei

**Comment by yincangshiwei** [comment]
> ummm, do you see the botton of queue? @camoody1 @yincangshiwei嗯，你看到 Queue 的按钮了吗？ @camoody1 @yincangshiwei

Yes, I can see the queue button.

**Comment by crystian** [comment]
please attach a screenshot
btw, what happend when press f5?
is an old instalation?

**Comment by EasyComfyui** [comment]
> please attach a screenshot btw, what happend when press f5? is an old instalation?

![image](https://github.com/user-attachments/assets/93e33fb9-1ee8-4bd3-82f9-ca957f19d2db)

**Comment by crystian** [comment]
but... the button is in the bottom! wt..

**Comment by yincangshiwei** [comment]
![image](https://github.com/user-attachments/assets/4c0163a8-2dd1-4aa5-8a9c-e1a264b3deb6)
https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.3.1

**Comment by crystian** [comment]
but.... which branch do you use? I use the release and I don't see that

**Comment by LukeG89** [comment]
@crystian You need to use the argument `--front-end-version Comfy-Org/ComfyUI_frontend@latest`

**Comment by EasyComfyui** [comment]
> Nhưng.... Bạn sử dụng nhánh nào? Tôi sử dụng bản phát hành và tôi không thấy điều đó

since version 1.30 ui has changed, i think it broke

**Comment by crystian** [comment]
ahhh, oka, but it's beta! 
sorry but, the current version is stable with stable version of comfy, I'll work on next, but no for now ¯\_(ツ)_/¯

**Comment by LukeG89** [comment]
@crystian At this point, since the front-end developers are always going to change something, isn't it a better solution to collaborate with them (make a pull request?) and integrate your Resouces Monitor as a core feature?

**Comment by camoody1** [comment]
@crystian I requested a fix on the Comfy end the other day and they told me it would not be completed because they were moving to this new GUI version. Today was the first day it went live. So, I suspect it will be moved into Stable very soon. Sorry about the extra work. 😢

**Comment by camoody1** [comment]
> ![image](https://private-user-images.githubusercontent.com/8185843/371075594-4c0163a8-2dd1-4aa5-8a9c-e1a264b3deb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDUxNDYsIm5iZiI6MTcyNzM0NDg0NiwicGF0aCI6Ii84MTg1ODQzLzM3MTA3NTU5NC00YzAxNjNhOC0yZGQxLTRhYTUtOGE5Yy1lMWEyNjRiM2RlYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMTAwMDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTU1M2Q3MmE0MmY2N2ZiZjcwMTZmYWIyYzQwOGU3ZTFmMDc2NzVlMjBhYjZlNmQ1YzM1M2I1ZjBmZDA1ODE3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.s_ZBXDflIFUXfXi6dKmFm7yobXLCU8h7daWeGW0_dWo) https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.3.1

How do I change the background image of my ComfyUI? I love the look you have on your screenshot.

**Comment by crystian** [comment]
I understand, on the weekend, I'll fix it
@LukeG89 would like to say "yes!", but as a software architect, I think they need to deliver a small group of functionality and bring the possibility to extend it with plugins/custon nodes, but the problem is the documentation about it hehe, I have to discovery how to do a lot stuffs, even I have to change the render because I found a better way to do it right now... 😆😭🫠

**Comment by yincangshiwei** [comment]
> > ![image](https://private-user-images.githubusercontent.com/8185843/371075594-4c0163a8-2dd1-4aa5-8a9c-e1a264b3deb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDUxNDYsIm5iZiI6MTcyNzM0NDg0NiwicGF0aCI6Ii84MTg1ODQzLzM3MTA3NTU5NC00YzAxNjNhOC0yZGQxLTRhYTUtOGE5Yy1lMWEyNjRiM2RlYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMTAwMDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTU1M2Q3MmE0MmY2N2ZiZjcwMTZmYWIyYzQwOGU3ZTFmMDc2NzVlMjBhYjZlNmQ1YzM1M2I1ZjBmZDA1ODE3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.s_ZBXDflIFUXfXi6dKmFm7yobXLCU8h7daWeGW0_dWo) https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.3.1
> 
> How do I change the background image of my ComfyUI? I love the look you have on your screenshot.

There are two ways
Type 1: Custom 'Settings' ->' Color Palette 'Template
The parameters of the template can be modified by searching for information, but the modified background is too coupled with the canvas adaptation, and the effect is not very good.
Type 2:
If the 'ComfyUI_fronend' extension is used, it is necessary to modify the ComfyUI/web_cCustoms versions/Comfy-Org_CmfyUI_fronend/latest version directory/user.css
If the 'ComfyUI_fronend' extension is not used, simply modify ComfyUI/web/user.css

user.css file content:
`/** Background image style **/
.graph-canvas-container {
    /* Image network URL */
    background-image: url('Image network URL');
    /* Local path of image
    background-image: url('../test.png');*/
    background-size: cover;
    background-repeat: no-repeat;
    /* Adjust the Y-axis position of the background image */
    background-position-y: 15%;
    /* Background transparency: self adjust with the opacity of the graph canvas below */
    opacity: 1;
}
#graph-canvas {
    /* Background transparency: self adjust with the opacity of the graph canvas container above */
    opacity: 0.8;
}`

**Comment by yincangshiwei** [comment]
> I understand, on the weekend, I'll fix it @LukeG89 would like to say "yes!", but as a software architect, I think they need to deliver a small group of functionality and bring the possibility to extend it with plugins/custon nodes, but the problem is the documentation about it hehe, I have to discovery how to do a lot stuffs, even I have to change the render because I found a better way to do it right now... 😆😭🫠

Great, looking forward to it.

**Comment by crystian** [comment]
ready for 3 versions, old one, current and next one!

please, check it! Thanks!

@LukeG89 @yincangshiwei @camoody1

**Comment by camoody1** [comment]
@crystian Well done! Thank you for your efforts.

**Comment by LukeG89** [comment]
Great job! Thanks @crystian! 🎉

**Comment by LukeG89** [comment]
I see that there are some graphical issues when opening workflow tabs and the docking queue menu:

https://github.com/user-attachments/assets/64c4d16f-129d-4624-b69e-3e0edef46d57

**Comment by camoody1** [comment]
@LukeG89 Don't dock the queue menu. 🤷🏽👍🏼

**Comment by LukeG89** [comment]
@camoody1 Great solution! 😆
But as you can see in my video, the issue still persists even if I don't.

**Comment by LukeG89** [comment]
Similar issue when increasing pixel height to the maximum:

![01](https://github.com/user-attachments/assets/fdbe9748-dc4f-44a3-aa32-6eecf17f1804)
![02](https://github.com/user-attachments/assets/3f2dee89-250d-46c9-b55a-8fa372fd01ee)

**Comment by crystian** [comment]
I'm not sure about it. What is the issue for you? the height or the stack? What do you think it should behave like? Because space is limited, I decided to stack it because the other option is scroll.
And remember this version of Comfy is still in beta, so they may change this behavior.

**Comment by LukeG89** [comment]
@crystian Watch the video and see what happens to the manager and show image feed buttons

**Comment by crystian** [comment]
Yes, I saw it, but that behavior is expected; for this reason, I added the height control.
They use the buttons the maximum height; it will happened with whatever extension that use that space ¯\_(ツ)_/¯

Insist: What do you think it should behave like?

**Comment by LukeG89** [comment]
@crystian Doesn't seem an expected behavior to stretch other extension buttons:
![bug](https://github.com/user-attachments/assets/43df4dd4-b9bb-4bd0-a7ac-6da4001e452a)

They should look like this:
![no_bug](https://github.com/user-attachments/assets/a557a81d-8b6e-43b5-bc63-a9f5f0e6eef1)
