### ISSUE TITLE
(IMPORT FAILED) Crystools

### ISSUE THREAD

**Issue by Balzzar** [crystian/ComfyUI-Crystools#128]
(IMPORT FAILED) Crystools.
Using ComfyUI_windows_portable.
Tried both automatic and manual install, same result: (IMPORT FAILED) Crystools.
Running on windows 11 with nvida gpu.

![image](https://github.com/user-attachments/assets/4d617ca5-e547-4695-9c41-68546137ed88)
![image](https://github.com/user-attachments/assets/d39244cd-21fb-4351-bd7f-72418770dda2)

**Comment by crystian** [comment]
I need more info on your console, please use the form: https://github.com/crystian/ComfyUI-Crystools/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
