### ISSUE TITLE
(IMPORT FAILED) Crystools

### ISSUE THREAD

**Issue by Balzzar** [crystian/ComfyUI-Crystools#129]
**Describe the bug**  
(IMPORT FAILED) Crystools

**To Reproduce**  
[workflow-relight-better-than-magnific---relighting-v5-better-ux-nSqO2P2ZmDQGwohEbgl3-risunobushi-openart.ai.json](https://github.com/user-attachments/files/17145807/workflow-relight-better-than-magnific---relighting-v5-better-ux-nSqO2P2ZmDQGwohEbgl3-risunobushi-openart.ai.json)

**Expected behavior**  
Can't run the workflow properly. (IMPORT FAILED) Crystools

**Screenshots**  
![image](https://github.com/user-attachments/assets/57e327be-3996-4b43-a3cb-415c60cbd94b)
![image](https://github.com/user-attachments/assets/c601a4b7-4fed-4bb2-aee7-fd5f23a80699)

**Error in console:**  
-Crystools
0.0 seconds (IMPORT FAILED): C:\Users\b\Desktop\ar\st\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools

ComfyUI Revision: 2652 [0c7c98a9] *DETACHED | Released on '2024-09-05'
ComfyUI-Manager (V2.51.1)
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Total VRAM 12288 MB, total RAM 65377 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
Using pytorch cross attention

**Comment by crystian** [comment]
I need more info from your logs, please, paste the on the startup here

**Comment by crystian** [comment]
I need more info ¯\_(ツ)_/¯
