### ISSUE TITLE
Use in Safari

### ISSUE THREAD

**Issue by StarLuckLee** [crystian/ComfyUI-Crystools#134]
I used the following command in the run_nvidia_gpu.bat file:

.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --listen 192.168.0.10

To achieve the function of accessing comfyui on other devices (imac M1 macOS Sequoia 15.0.1);

However, the data of crystools in Safari is all 0%, it does not work (as shown in the picture)

<img width="411" alt="image" src="https://github.com/user-attachments/assets/2b1acfd4-6427-4780-8361-70090ad62bf0">

I hereby come to inquire about the reason, thank you very much.

**Comment by crystian** [comment]
I need more info, please fill the form when you create a new issue
