### ISSUE TITLE
段错误 (核心已转储)

### ISSUE THREAD

**Issue by yyq19990828** [crystian/ComfyUI-Crystools#137]
**Versions:**  
Copy the output of the console (4 parts), like this:
```
## ComfyUI-Manager: installing dependencies done.                                                                                                                                             
** ComfyUI startup time: 2024-10-21 18:02:26.417008
** Platform: Linux
** Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
** Python executable: /home/yangyiqing/miniconda3/envs/comfyui/bin/python
** ComfyUI Path: /media/dell/DATA/yiqing/铁锅炖整合包8月版/ComfyUI
** Log path: /media/dell/DATA/yiqing/铁锅炖整合包8月版/ComfyUI/custom_nodes/ComfyUI-Crystools/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /media/dell/DATA/yiqing/铁锅炖整合包8月版/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /media/dell/DATA/yiqing/铁锅炖整合包8月版/ComfyUI/custom_nodes/ComfyUI-Marigold
   0.0 seconds: /media/dell/DATA/yiqing/铁锅炖整合包8月版/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   1.0 seconds: /media/dell/DATA/yiqing/铁锅炖整合包8月版/ComfyUI/custom_nodes/ComfyUI-Manager

Set cuda device to: 1
Total VRAM 24260 MB, total RAM 257551 MB
pytorch version: 2.4.0+cu121
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention

```

![image](https://github.com/user-attachments/assets/797e9c4c-83ca-413a-9fa7-9e13cdf23443)

```
### Loading: ComfyUI-Manager (V2.51.8)
### ComfyUI Revision: 2776 [83ca8911] | Released on '2024-10-20'

```

**Additional context**

**Comment by crystian** [comment]
more info is needed

**Comment by yyq19990828** [comment]
after intsalll a custom node called https://github.com/EvilBT/ComfyUI_SLK_joy_caption_two
some Dependencies have been modified as bellow:

## ComfyUI-Manager: EXECUTE => ['/home/yangyiqing/miniconda3/envs/comfyui/bin/python', '-m', 'pip', 'install', 'huggingface_hub==0.23.4']                                                     
 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple                                                                                                                                 
 Collecting huggingface_hub==0.23.4                                                                                                                                                           
   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/69/d6/73f9d1b7c4da5f0544bc17680d0fa9932445423b90cd38e1ee77d001a4f5/huggingface_hub-0.23.4-py3-none-any.whl (402 kB)                 
            Installing collected packages: huggingface_hub                                                                                                                                    
   Attempting uninstall: huggingface_hub                                                                                                                                                      
     Found existing installation: huggingface-hub 0.24.5                                                                                                                                      
     Uninstalling huggingface-hub-0.24.5:                                                                                                                                                     
       Successfully uninstalled huggingface-hub-0.24.5                                                                                                                                        
[!] ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.            
 Successfully installed huggingface_hub-0.23.4                                                                                                                                                
[!] datasets 2.21.0 requires requests>=2.32.2, but you have requests 2.31.0 which is incompatible.                                                                                            
                                                                                                                                                                                              
## ComfyUI-Manager: EXECUTE => ['/home/yangyiqing/miniconda3/envs/comfyui/bin/python', '-m', 'pip', 'install', 'transformers>=4.44.0']                                                        
 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple                                                                                                                                 
                                                                                                                                                                                              
## ComfyUI-Manager: EXECUTE => ['/home/yangyiqing/miniconda3/envs/comfyui/bin/python', '-m', 'pip', 'install', 'numpy==1.26.4']                                                               
 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple                                                                                                                                 
 Collecting numpy==1.26.4                                                                                                                                                                     
   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3a/d0/edc009c27b406c4f9cbc79274d6e46d634d139075492ad055e3d68445925/numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86
_64.whl (18.3 MB)                                                                                                                                                                             
 Installing collected packages: numpy                                                                                                                                                         
   Attempting uninstall: numpy                                                                                                                                                                
     Found existing installation: numpy 1.25.2                                                                                                                                                
     Uninstalling numpy-1.25.2:                                                                                                                                                               
       Successfully uninstalled numpy-1.25.2                                                                                                                                                  
[!]  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.           
Successfully installed numpy-1.26.4                                                                                                                                                           
[!] datasets 2.21.0 requires requests>=2.32.2, but you have requests 2.31.0 which is incompatible.                                                                                            
[!] inference-cli 0.19.0 requires py-cpuinfo>=9.0.0, but you have py-cpuinfo 3.3.0 which is incompatible.                                                                                     
[!] inference-cli 0.19.0 requires rich<=13.5.2, but you have rich 13.9.2 which is incompatible.                                                                                               
[!] mediapipe 0.10.14 requires protobuf<5,>=4.25.3, but you have protobuf 3.20.3 which is incompatible.                                                                                       
[!] inference-gpu 0.19.0 requires packaging~=24.0, but you have packaging 23.2 which is incompatible.                                                                                         
[!] inference-gpu 0.19.0 requires py-cpuinfo>=9.0.0, but you have py-cpuinfo 3.3.0 which is incompatible.                                                                                     
[!] inference-gpu 0.19.0 requires rich<=13.5.2, but you have rich 13.9.2 which is incompatible.                                                                                               
[!] inference-gpu 0.19.0 requires setuptools<=72.1.0,>=70.0.0, but you have setuptools 65.0.0 which is incompatible.                                                                          
[!] xformers 0.0.28.post1 requires torch==2.4.1, but you have torch 2.4.0 which is incompatible.                                                                                              
[!] simple-lama-inpainting 0.1.2 requires pillow<10.0.0,>=9.5.0, but you have pillow 10.4.0 which is incompatible.  

## ComfyUI-Manager: EXECUTE => ['/home/yangyiqing/miniconda3/envs/comfyui/bin/python', '-m', 'pip', 'install', 'sentencepiece==0.2.0']                                                        
 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple                                                                                                                                 
                                                                                                                                                                                              
## ComfyUI-Manager: EXECUTE => ['/home/yangyiqing/miniconda3/envs/comfyui/bin/python', '-m', 'pip', 'install', 'pillow>=10.4.0']                                                              
 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple                                                                                                                                 
                                                                                                                                                                                              
## ComfyUI-Manager: EXECUTE => ['/home/yangyiqing/miniconda3/envs/comfyui/bin/python', '-m', 'pip', 'install', 'bitsandbytes>=0.44.1']                                                        
 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple                                                                                                                                 
 Collecting bitsandbytes>=0.44.1                                                                                                                                                              
   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e4/e6/ccb84da7ffaf208a71c2c3c8e1120b34759df640db959660be9a98505eb4/bitsandbytes-0.44.1-py3-none-manylinux_2_24_x86_64.whl (122.4 MB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.4/122.4 MB 1.1 MB/s eta 0:00:00                                                                                                            
                        Installing collected packages: bitsandbytes                                                                                                                           
   Attempting uninstall: bitsandbytes                                                                                                                                                         
     Found existing installation: bitsandbytes 0.43.3                                                                                                                                         
     Uninstalling bitsandbytes-0.43.3:                                                                                                                                                        
       Successfully uninstalled bitsandbytes-0.43.3                                                                                                                                           
 Successfully installed bitsandbytes-0.44.1                                                                                                                                                   
                                                                                                                                                                                              
## ComfyUI-Manager: EXECUTE => ['/home/yangyiqing/miniconda3/envs/comfyui/bin/python', '-m', 'pip', 'install', 'peft>=0.12.0']                                                                
 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple                                                                                                                                 
                                       Installation was successful.                                                                                                                           
After restarting ComfyUI, please refresh the browser.                                                                                                                                         
                                                                                                                                                                                              
Restarting... [Legacy Mode]

**Comment by yyq19990828** [comment]
@crystian
