### ISSUE TITLE
系统找不到指定的文件

### ISSUE THREAD

**Issue by speen999** [crystian/ComfyUI-Crystools#144]
D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\nodes\image.py:350: SyntaxWarning: invalid escape sequence '\/'
  "Description": "More info: https:\/\/www.instagram.com\/crystian.ia", # "\/" is for escape / on json
  Error =>  [WinError 2] 系统找不到指定的文件。

**Comment by crystian** [comment]
I don't understand Chinese, please fill the issue in English, thanks
