### ISSUE TITLE
Switch Any Node | Thought this acts as a (e.g.workflow) real switch, or is it a bug

### ISSUE THREAD

**Issue by WordfromtheWise** [crystian/ComfyUI-Crystools#151]
Hi there, 

In my case i wanted to have a switch so when set to TRUE it creates a Final Save Image
and when set to FALSE it only shows the render imgae as a preview.
I tried all possible combinations/tricks i could come up with (e.g rerouting when FALSE back to the VAE and more) to no result.
So is this a bug or what is this switch for? 

I included a screenshot of what i want
![grafik](https://github.com/user-attachments/assets/3a94592c-082d-496c-a60d-7d324707b375)

and also one of how the error looks 
![grafik](https://github.com/user-attachments/assets/e2542f79-f19c-465a-93f5-a1d685cf2e6a)

SysInfo: 
[Prompt Server] web root: g:\ComfyUI_windows_portable\ComfyUI\web
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: AMD Ryzen 9 3900X 12-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4090
[Crystools INFO] NVIDIA Driver: 566.14
 Loading: ComfyUI-Manager (V2.53)
 ComfyUI Revision: 2874 [20a560eb] | Released on '2024-11-29'

PS: Within COMFYUI the last Update is set to 2024-11-09 
![grafik](https://github.com/user-attachments/assets/82cec38b-d00b-469e-870a-9f3979a68f88)

## STATS/DEBUG part should be standard in ComfyUI
![grafik](https://github.com/user-attachments/assets/74fc75d4-f3b8-407c-87ad-b2c7a4c6d8e5)

**Comment by LukeG89** [comment]
@WordfromtheWise It doesn't work like that. The switch has 2 inputs and 1 output, and the switch just selects which input goes to the output.

For your purpose, you need a switch with 1 input and 2 outputs. Someone requested it, but it's still not available in Crystools: https://github.com/crystian/ComfyUI-Crystools/issues/136

As an alternative, you could use `Inversed Switch (Any)` from [ComfyUI-Impact-Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack)

![image](https://github.com/user-attachments/assets/8d414ad9-f5be-4a45-bb61-51f972f23e9c)

**Comment by SirVeggie** [comment]
@WordfromtheWise You should close the issue.
