### ISSUE TITLE
No GPU → no stats at all

### ISSUE THREAD

**Issue by mord0d** [crystian/ComfyUI-Crystools#23]
**Describe the bug**  
```
[Crystools ERROR] Could not init pynvml.NVML Shared Library Not Found
[Crystools WARNING] No GPU with CUDA detected.
```

`pynvml` installed (thanks to `requirements.txt`) but it's useless for me as I have no GPU.

No stats at all: no CPU, no RAM, no HDD. Moreover, there's nothing about Crystools in settings popup.

**To Reproduce**  
Reproducible with empty or default workflow.

**Expected behavior**  
If there's no GPU (or `pynvml` import failed), just don't try to collect GPU/VRAM stats and don't show them, *but show other stats*.

**Error in console:**  
There's no traceback, only output that I've posted above.

**Versions:**  
```
** Python version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
```

```
Total VRAM 32091 MB, total RAM 32091 MB
Set vram state to: DISABLED
Device: cpu
```

```
[Crystools INFO] Crystools version: 1.10.0
[Crystools INFO] CPU: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz - Arch: x86_64 - OS: Linux 6.1.0-16-amd64
[Crystools ERROR] Could not init pynvml.NVML Shared Library Not Found
[Crystools WARNING] No GPU with CUDA detected.
```

```
### Loading: ComfyUI-Manager (V2.2.1)
### ComfyUI Revision: 1915 [ee2c5fa7] | Released on '2024-01-16'
```

**Comment by crystian** [comment]
Good report!
I tried it, but I could not reproduce it. Do you "play" with the settings? (cpu, ram or hdd)
What do you see on comfy?

**Comment by crystian** [comment]
![image](https://github.com/crystian/ComfyUI-Crystools/assets/3886806/684236fc-0027-4f1f-9741-5bc39d3b28b4)
with CPU and a raise a similiar exception

**Comment by crystian** [comment]
umm, does not appear on settings? please. press F12 on your browser and see what happens on the console when press F5

**Comment by mord0d** [comment]
@crystian,

> Do you "play" with the settings? (cpu, ram or hdd)

As I said before, there's no settings for Chrystools in settings popup/menu, so I can't "play" with them.

> see what happens on the console

Sorry, didn't think about JavaScript…

A lot of warnings (+2 every ≈1 second):

```
api.js:152
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 0.2, "ram_total": 33649987584, "ram_used": 575188992, "ram_used_percent": 3.1, "hdd_total": 33606692864, "hdd_used": 3157155840, "hdd_used_percent": 9.9, "device_type": "cpu", "gpus": [{"gpu_utilization": 0, "vram_total": 0, "vram_used": 0, "vram_used_percent": 0}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:147:18)
(
```

**Comment by crystian** [comment]
Good, I need the first lines of the javascript console. Can you copy-paste them?

**Comment by mord0d** [comment]
> Can you copy-paste them?

It's not easy to just copy-paste… [There's a full console log](https://github.com/crystian/ComfyUI-Crystools/files/13977737/172.22.2.14-1705587554075.log).

But…

> ![image](https://private-user-images.githubusercontent.com/3886806/297496270-684236fc-0027-4f1f-9741-5bc39d3b28b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDYwMTgsIm5iZiI6MTcwNTU0NTcxOCwicGF0aCI6Ii8zODg2ODA2LzI5NzQ5NjI3MC02ODQyMzZmYy0wMDI3LTRmMWYtOTc0MS01YmMzOWQzYjI4YjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDI0MTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTAzOThmNTFjYWJmNjlkOTU0M2UzNzA2NGYzZTJlZTU3MzEzNWViYjRlZTM2NWFlMWRkYjg1NmNkYzJjZjVjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dcANq4t9G-eaq6-tbL7RcBYLP3Xm8SRlSH_dw8SwCXg)
> with CPU and a raise a similiar exception

I see that my issue is invalid. ☺  
After several hours of debugging I managed to fix the errors.

![crystools](https://github.com/crystian/ComfyUI-Crystools/assets/48280847/4e484faf-3940-4d2a-a40f-4527dab4f120)

**Thanks for your help and your great tools!**

**Comment by crystian** [comment]
@mord0d oh nice! hehe it's magic! thanks for your feedback!
