### ISSUE TITLE
Feature Request: SwitchMask

### ISSUE THREAD

**Issue by godly** [crystian/ComfyUI-Crystools#25]
**Is your feature request related to a problem? Please describe.**
A connection from a 'Mask' output via a 'Reroute' node to 'SwitchAny' is not possible.
A direct connection from 'Mask' into 'SwitchAny' works fine.

**Describe the solution you'd like**
I'd like to have a 'SwitchMask' node which accepts 'Mask' input from 'Reroute' nodes.

**Describe alternatives you've considered**
I don't know enough about the node routing '/ handling :( . A working "Any" ---> "Reroute" ---> "SwitchAny" option would make the existing SwitchImage, SwitchLatent, ... obsolete. Not sure if this is possible at all.

**Additional context** (lt;dr)
I try to group things together. So I have an optional 'Custom Mask' input together with a 'Primitive boolean' selector. Anyhow the internal routing doesn't work as a direct connection from a 'Mask' output into 'SwitchAny' is needed.

I use for example 'ClipSeg' to automatically create a mask. Sometimes this leads to bad resulsts and then I use 'Sam Detector' or 'Mask Editor' outside of the group to create the mask. Then I'd like to feed the Mask into the group through a 'Reroute' node to enter the group before connecting it to a swtich.
For images this works fine with the 'Primitive boolean' selector, anyhow there is a dedicated 'SwitchImage' node which I use in this case.

Thanks for sharing these cool nodes!

**Comment by crystian** [comment]
Ok, I'll do it these days, thanks.

**Comment by crystian** [comment]
Could you try the new version? 1.11.0
