### ISSUE TITLE
[Bug] Cannot route CPipeAny -> Reroute -> AnySwitch

### ISSUE THREAD

**Issue by copejon** [crystian/ComfyUI-Crystools#27]
**Describe the bug**  
As a user, I want to cleanly connect CPipeAny output to a SwitchAny input via a comfyUI reroute node.  It is possible to pass the CPipeAny output to the Reroute node. It is also possible to connect a CPipeAny output directly to a SwitchAny input. But it is not possible to connect the output of the reroute to the SwitchAny input.

e.g.
```text
Works as expected:

... -> To/Edit CPipeAny -> SwitchAny --> ...

Does not work as expected:

... -> To/Edit CPipeAny -> Reroute -X-> SwitchAny --> ...
```

**To Reproduce**  
__Please attach a workflow file to make it easier for others to reproduce the error!__

[ComfyUI workflow (9).json](https://github.com/crystian/ComfyUI-Crystools/files/14054058/ComfyUI.workflow.9.json)

**Expected behavior**  
The To/Edit CPipeAny output can connect to a reroute which can then connect to a AnySwitch.

**Screenshots**  
See workflow

**Error in console:**  
No error logged in console.

**Versions:**  
Copy the output of the console (4 parts), like this:
```
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
```
```
Total VRAM 12287 MB, total RAM 130996 MB
Set vram state to: NORMAL_VRAM
```
```
[Crystools INFO] Crystools version: [1.9.2](http://1.9.0.2/)
[Crystools INFO] CPU: Intel(R) Core(TM) i5-9600K CPU @ [3.70GHz](http://3.70ghz/) - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 2080 SUPER
[Crystools INFO] NVIDIA Driver: [546.33](http://546.33/)
```
```
### Loading: ComfyUI-Impact-Pack ([V4.66.4)](http://v4.66.4)/)
### Loading: ComfyUI-Impact-Pack (Subpack: [V0.4)](http://v0.4)/)
```

**Additional context**

**Comment by crystian** [comment]
yeap, it is a known issue from comfyUI, you can use this extension that has another rerouter
https://github.com/rgthree/rgthree-comfy?tab=readme-ov-file#reroute
