### ISSUE TITLE
No module named 'deepdiff'

### ISSUE THREAD

**Issue by Arthur9291619** [crystian/ComfyUI-Crystools#29]
when i download the nodes put it to my comfyui nodes packge,it does not work ,the powershell show it like this:
Cannot import E:\AI\Stable Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools-main module for custom nodes: No module named 'deepdiff'

How to solve this problem?

**Comment by crystian** [comment]
ummm, do you follow the instructions? did you install dependencies?

https://github.com/crystian/ComfyUI-Crystools?tab=readme-ov-file#installation

**Comment by Sizolity** [comment]
actually, you should try fix it in Comfy Manager  before you consider reinstalling
