### ISSUE TITLE
Unable to Install Crystools via Manager or Manual

### ISSUE THREAD

**Issue by ezoosk** [crystian/ComfyUI-Crystools#31]
**Describe the bug**  
ComfyUI is installed via Pinokio - most if not all other modules install with no issues, except for Crystools unfortunately

I've attempted to install via Manager, Disable, Try Fix, Uninstall, Reinstall, no difference.

Also tried deleting Crystools in ComfyUI Custom Modules and installing manually via Git. Still no dice unfortunately

Would love to get your awesome tools to work!

Win 11 RTX 3090

**Comment by crystian** [comment]
Sorry but I won't fix it.

I'm not sure for what reason people using this kind of software, It can port a troyan so easly.

Did you run?: 
```
pip install -r requirements.txt
```

**Comment by ezoosk** [comment]
Yep. I'm installing comfyui fresh just so hopefully everything will work (and thanks for the tip on the risk potential)

**Comment by ezoosk** [comment]
Everything works now. Cheers and thanks again

**Comment by crystian** [comment]
thanks for your feeback!
