### ISSUE TITLE
Crystools not working on StableSwarmUI

### ISSUE THREAD

**Issue by Soliver84** [crystian/ComfyUI-Crystools#32]
Crystools not working on StableSwarmUI, Standalone Working

![image](https://github.com/crystian/ComfyUI-Crystools/assets/11579411/4eae78f2-1421-4451-af96-ee9acff73712)

**Comment by crystian** [comment]
I'll try, but I don't support this kind of (complicated) configuration.

**Comment by crystian** [comment]
I don't have time sorry :(
