### ISSUE TITLE
Rename Pipe any fields to source of data similar to reroute

### ISSUE THREAD

**Issue by gonzalu** [crystian/ComfyUI-Crystools#34]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
On the PipeTo and PipeFrom nodes, the ability for the fields to automatically adjust the name from "any_1" etc. to the data type (model, clip, VAE, etc.) 

**Describe alternatives you've considered**
Currently I am using rgthree reroute which gives me a lot of control but limited to one source

Thank you.

**Comment by crystian** [comment]
I'll check next week, thanks for the report!

**Comment by crystian** [comment]
Sorry, but because it is "any", rgthree validates it, and they can be connected
