### ISSUE TITLE
CPU and GPU data and resource managers do not match

### ISSUE THREAD

**Issue by mufenglyf** [crystian/ComfyUI-Crystools#37]
Like the image below, GPU and CPU data will fluctuate, but there is a significant difference
![20240303133507](https://github.com/crystian/ComfyUI-Crystools/assets/141204761/718b5513-4cff-41cd-96ab-58e79799581a)

**Comment by crystian** [comment]
I understand, but I use utilities to get this information for the CPU I use psutil.cpu_percent and for GPU I use pynvml.nvmlDeviceGetUtilizationRates (from the driver), so I can't improve it; I only show the data from there.

¯\_(ツ)_/¯

If you find a better way to get this information, it is welcome!
