### ISSUE TITLE
Add AMD GPU and vram display

### ISSUE THREAD

**Issue by tjzoo111** [crystian/ComfyUI-Crystools#38]
The terminal can obtain information through rocm-smi, but unfortunately I don’t know python

**Comment by crystian** [comment]
Hi, sorry but I won't do that, I cannot test it :(
If you want to add, be free to make a PR

**Comment by tjzoo111** [comment]
![2024-03-11 23-01-47 的屏幕截图](https://github.com/crystian/ComfyUI-Crystools/assets/147966162/5e259624-b862-4937-8e17-fb0c694d7f2e)
My code is very poor and can only be used on linux amdgpu

**Comment by tjzoo111** [comment]
Yes, the GPU is 0% when it is not working, and it is 100% when the GPU is working.

**Comment by crystian** [comment]
can you share your code here please?
