### ISSUE TITLE
When I use the CVH batch management module, the total time is not counted correctly.

### ISSUE THREAD

**Issue by H-Bole** [crystian/ComfyUI-Crystools#39]
**Is your feature request related to a problem? Please describe.**
When I use the batch management of the ComfyUI-VideoHelperSuite plugin (which can effectively avoid errors caused by running out of memory when processing videos), the total time count for the entire workflow is wrong

**Describe the solution you'd like**
This makes it impossible for me to count the efficiency of the entire workflow unless I slowly calculate the time myself against the console output, so I want you to be able to count the total time correctly

**Describe alternatives you've considered**
I don't know of a similar workaround

**Additional context**
Here's an example of my batch management workflow：

![example](https://github.com/crystian/ComfyUI-Crystools/assets/102267145/07a1951c-f919-4a69-a2a6-45ee21f9117d)
The time now counted is actually the time of the last batch processed, not the total time of the total batch

**Comment by H-Bole** [comment]
Sorry, the workflow export failed just now, now re-upload
[example.json](https://github.com/crystian/ComfyUI-Crystools/files/14506230/example.json)
![workflow](https://github.com/crystian/ComfyUI-Crystools/assets/102267145/63d5de37-73ec-4395-ae6d-93ff4f0e9524)

**Comment by H-Bole** [comment]
[example.json](https://github.com/crystian/ComfyUI-Crystools/files/14506230/example.json)
![workflow](https://github.com/crystian/ComfyUI-Crystools/assets/102267145/63d5de37-73ec-4395-ae6d-93ff4f0e9524)
Sorry, the workflow export failed just now, now re-upload

**Comment by crystian** [comment]
I understand, but I used the events of comfyui for this; I don't have control over the "how," sorry, I can't fix it :(

**Comment by H-Bole** [comment]
fine。
