### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by tetsuoo-online** [crystian/ComfyUI-Crystools#4]
Sigh...it's a classic now :/ And it's not just these scripts, it happens more and more often with some others. Last time I had this, it was some libraries missing, this time it's 'IFD' and 'PIL'
I tried both manual and Manager method

 - ComfyUI Revision 1878, updated today but it didn't work before neither.
 
 Python 3.10.13
Torch version 2.1.2+cu118

![image](https://github.com/crystian/ComfyUI-Crystools/assets/45845308/c36e5eda-91ce-45fa-b5fe-46ec8460242f)

![image](https://github.com/crystian/ComfyUI-Crystools/assets/45845308/7184c54f-a8ac-4062-8346-bcffc7cdc9dd)

**Comment by crystian** [comment]
let me check right now

**Comment by crystian** [comment]
I've reinstalled with the same versions to you and can't reproduce it :(

**Comment by crystian** [comment]
I think is the version of Pillow (I use the same as ComfyUI), you can check the version with:
`pip show pillow`

in my case (9.5.0):
```
Name: Pillow
Version: 9.5.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Jeffrey A. Clark (Alex)
Author-email: aclark@aclark.net
License: HPND
```

**Comment by crystian** [comment]
I check the [code](https://github.com/python-pillow/Pillow/blob/9.4.0/src/PIL/ExifTags.py) of that library, and it has this class in 9.4.0, that is the problem.

you can update it with: `pip install pillow==9.5.0`

I recommend a clean installation, it sounds an old installation

Let me know if it works

**Comment by rycon** [comment]
@crystian, installing pillow 9.5.0 fixed the same issue for me.

**Comment by tetsuoo-online** [comment]
oh yeah it's at least 1 week old, unacceptable xD
Just how many times do I need to reinstall everything, wait I know, every time I install something new in it xDDD
I'm sad I need to become a Github expert to make things work, where should I update pillow, just open a CMD anywhere ? (which means it's gonna update in Python folder), or in some venv/embeded_python folder ? Or in ComfyUI-Crystools ?
If I do it in general Python, Pillow is now downgraded from 10.0 to 9.5, is that alright ? Help x)

**Comment by crystian** [comment]
@tetsuoo-online, welcome to python world! xDD

There are lots of variables when you install your dependencies that are saved into your Venv folder so that you may have old resources in that place; when you reinstall, what does that mean? only comfyui or python or venv folder? hehe, lots of variables

Do you use a particular folder of venv for comfyui or use the same for your system?

if you use a particular one you need to activate it first and after install the dependency

I recommend using a special folder for venv with all your dependencies, I have a bat with this:

```
set PYTHON=e:\Workstation\Python310\python.exe
set VENV_DIR=e:\AI\SD\comfyUI\.env

%PYTHON% -m venv %VENV_DIR%
call %VENV_DIR%\Scripts\activate.bat

...

call %VENV_DIR%\Scripts\deactivate.bat
```

This recommendation is not for my extension, this is for the python ecosystem.

**Comment by crystian** [comment]
please update my extension @tetsuoo-online y put a requirement as minimum version

**Comment by crystian** [comment]
I made this gist for share my scripts of comfyUI, it may give you ideas :)

https://gist.github.com/crystian/c18a9cf6c9f3e7791cf29751f2240827
