### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by playlogitech** [crystian/ComfyUI-Crystools#40]
**Describe the bug**  
Extension impossible to install on the latest version comfyUI

**To Reproduce**  
__Please attach a workflow file to make it easier for others to reproduce the error!__

**Expected behavior**  

**Screenshots**  

**Error in console:**  
[Crystools INFO] Crystools version: 1.11.0
Traceback (most recent call last):
  File "C:\Users\Playg\Desktop\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Playg\Desktop\ComfyUI\custom_nodes\ComfyUI-Crystools\__init__.py", line 18, in <module>
    from .nodes.image import CImagePreviewFromImage, CImageLoadWithMetadata, CImageGetResolution, CImagePreviewFromMetadata, \
  File "C:\Users\Playg\Desktop\ComfyUI\custom_nodes\ComfyUI-Crystools\nodes\image.py", line 11, in <module>
    from PIL.ExifTags import TAGS, GPSTAGS, IFD
ImportError: cannot import name 'IFD' from 'PIL.ExifTags' (C:\Users\Playg\Desktop\ComfyUI\venv\lib\site-packages\PIL\ExifTags.py)

Cannot import C:\Users\Playg\Desktop\ComfyUI\custom_nodes\ComfyUI-Crystools module for custom nodes: cannot import name 'IFD' from 'PIL.ExifTags' (C:\Users\Playg\Desktop\ComfyUI\venv\lib\site-packages\PIL\ExifTags.py)
### Loading: ComfyUI-Manager (V2.10.2)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 2070 [b1a16d45] | Released on '2024-03-18'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...

[rgthree] Loaded 34 fantastic nodes.
[rgthree] Will use rgthree's optimized recursive execution.

Import times for custom nodes:
   0.0 seconds: C:\Users\Playg\Desktop\ComfyUI\custom_nodes\ComfyUI-Crystools-save
   0.0 seconds: C:\Users\Playg\Desktop\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds (IMPORT FAILED): C:\Users\Playg\Desktop\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.2 seconds: C:\Users\Playg\Desktop\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: C:\Users\Playg\Desktop\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.0 seconds: C:\Users\Playg\Desktop\ComfyUI\custom_nodes\ComfyUI-SUPIR

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Versions:**  
Copy the output of the console (4 parts), like this:
```
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
```
```
Total VRAM 12287 MB, total RAM 130996 MB
Set vram state to: NORMAL_VRAM
```
```
[Crystools INFO] Crystools version: 1.9.2
[Crystools INFO] CPU: AMD Ryzen 9 5950X 16-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3080 Ti
[Crystools INFO] NVIDIA Driver: 546.33
```
```
### Loading: ComfyUI-Manager (V1.25.3)
### ComfyUI Revision: 1886 [6a10640f] | Released on '2024-01-08'
```

**Additional context**

**Comment by playlogitech** [comment]
nvm, issue occurs only when installing through comfy manager, i fixed it with pip install -r requirements.txt

**Comment by crystian** [comment]
Thanks for your reporting, but I set the version minimum to fix this issue on requirements, and that will work.
