### ISSUE TITLE
Temperature sensors for GPU and CPU (+ Live VRAM sensor)

### ISSUE THREAD

**Issue by ArgentVASIMR** [crystian/ComfyUI-Crystools#41]
Given that Stable Diffusion puts a lot of stress onto the GPU, being able to see the temperature from within ComfyUI would be very useful.

I personally lack the knowledge necessary to make a PR for this, but if you're unsure where to start, you could check https://github.com/meap158/ComfyUI-GPU-temperature-protection.

Additionally, VRAM usage should also have a live sensor available instead of being relegated to a node.

**Comment by crystian** [comment]
it's good one, I'll check to do it! Thanks!

**Comment by crystian** [comment]
"Additionally, VRAM usage should also have a live sensor available instead of being relegated to a node.", sorry, I didn't understand, can you explain please, thanks

**Comment by ArgentVASIMR** [comment]
> "Additionally, VRAM usage should also have a live sensor available instead of being relegated to a node.", sorry, I didn't understand, can you explain please, thanks

Oh, weird, I must've hallucinated something. Turns out there is a live VRAM monitor that was always present; disregard that part, sorry!
