### ISSUE TITLE
RuntimeError: <asyncio.locks.Lock object at 0x000002A79E6B2B50 [unlocked, waiters:1]> is bound to a different event loop

### ISSUE THREAD

**Issue by KewkLW** [crystian/ComfyUI-Crystools#48]
A couple of us wrote this up in the main comfy repo. However, investigating further disabling crystools fixed the issue. 

 https://github.com/comfyanonymous/ComfyUI/issues/3232

**Comment by KewkLW** [comment]
I may have jumped the gun and I apologize if this isn't your issue. I'm still looking into it as, it's still happening but inconsistently now.

**Comment by crystian** [comment]
Sorry, this weekend I'm going to review this, if you have more information, are welcome!
