### ISSUE TITLE
Node installed, seems to work in the terminal, but node not found

### ISSUE THREAD

**Issue by VOOM108** [crystian/ComfyUI-Crystools#52]
**Describe the bug**  
I installed the node via manager and restarted Comfy. When starting up, I see this kind of info on the terminal window:
[Crystools INFO] Crystools version: 1.12.0
[Crystools INFO] CPU: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3060
[Crystools INFO] NVIDIA Driver: 552.22

I cannot find the node, though, to actually show the info in the GUI

**Versions:**  
Copy the output of the console (4 parts), like this:
```
** Python version: 3.10.14 | packaged by Anaconda, Inc. | (main, Mar 21 2024, 16:20:14) [MSC v.1916 64 bit (AMD64)]
```
```
Total VRAM 12288 MB, total RAM 65391 MB
Set vram state to: NORMAL_VRAM
```
```
see above
```
```
### Loading: ComfyUI-Manager (V2.25.1)
### ComfyUI Revision: 2160 [72508a8d] | Released on '2024-05-04'
```

**Comment by crystian** [comment]
so strange, still happening?
