### ISSUE TITLE
API.js Unhandled Error

### ISSUE THREAD

**Issue by Piscabo** [crystian/ComfyUI-Crystools#54]
[Crystools INFO] Crystools version: 1.12.0
[Crystools INFO] CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3060
[Crystools INFO] NVIDIA Driver: 552.22

![image](https://github.com/crystian/ComfyUI-Crystools/assets/123719842/989d2e50-9fe7-4325-b1c7-e5f48dc343a0)

Prevents WEBUI from starting timeously.

**Comment by crystian** [comment]
umm, so strange, it does not happen to me, please, use a cognito browser to check it
