### ISSUE TITLE
[Feature request] Switching outputs

### ISSUE THREAD

**Issue by ANGJustinl** [crystian/ComfyUI-Crystools#55]
**Is your feature request related to a problem?**  Nope :(
Sometime I want to end up without upscaling and just make the image out to the saving node, I think its good to have a 1 in multiple out switch to fill this

**Describe the solution you'd like**
One "anything" in and multiple outputs "anything", a "int" for how many outpoints

**Comment by crystian** [comment]
Yes, I tried it, but it is complicated; PR is welcome! :)

**Comment by ANGJustinl** [comment]
thx xd
