### ISSUE TITLE
Position in browser screen

### ISSUE THREAD

**Issue by Metairieman55** [crystian/ComfyUI-Crystools#62]
This is a minor annoyance. In the browser screen, the Queue Prompt panel (in regular browser mode) blocks the "Move" icon for the panel. I've checked off the "Save menu position", too. However, if I "F11" to full screen, I can get to the "Move." I use Firefox. Is there a setting to allow the "Move" in a normal screen environment?

Nothing crucial. Thanks for any input. I do love the meters, though.

**Comment by crystian** [comment]
Hi @Metairieman55 I understood, but it is a natural behavior of comfyui, not my extension, btw, try without my extension to known that

**Comment by Metairieman55** [comment]
That's fine and thanks for your quick reply. If you get any further inquiries about the same, just tell them to 'full window" the browser and they'll get to the "hidden" controls.

Thanks!
