### ISSUE TITLE
 (IMPORT FAILED) Crystools

### ISSUE THREAD

**Issue by Kidz0r** [crystian/ComfyUI-Crystools#64]
Hi, I have an issue with Crystools :( In cmd it shows its loaded succesfully however in ComfyUI manager it says (IMPORT FAILED),

anyone encountered the same issue ? do you have any solution please ?

<img width="446" alt="image" src="https://github.com/crystian/ComfyUI-Crystools/assets/152255004/b897ca0f-2e3e-4cdb-a1ba-e496ae5dbefa">

**Comment by pphoto808** [comment]
Same issue. No solution

**Comment by YofarDev** [comment]
For me the solution was to pip -r requirements.txt in the Crystools folder

**Comment by crystian** [comment]
I don't know for what, but sometimes people report that the dependencies were not installed
¯\_(ツ)_/¯
