### ISSUE TITLE
Laptop monitor errors

### ISSUE THREAD

**Issue by ptmarks** [crystian/ComfyUI-Crystools#68]
Great tool! Super handy, however when I'm working on my laptop Crystools inevitably will through errors around power and the monitor.

It would be nice if Crystools didn't throw errors when my laptop monitor turns off while a ComfyUI gen is happening. I shouldn't have to keep the monitor active during a long generation to avoid Crystools errors. I also shouldn't get errors if I'm running on battery vs being plugged in.

Is there a way to work around this?

Thank you for your help!

**Comment by crystian** [comment]
I need more info, but, is an issue from the driver of nvidia :(
