### ISSUE TITLE
Event loop error in asyncio Lock

### ISSUE THREAD

**Issue by dcondic** [crystian/ComfyUI-Crystools#7]
**Describe the bug**
After update 1/8/2024 3:44AM it worked for a while but now gives error every time
asyncio.locks.lock object at 0x00000217c74b1360 [unlocked, waiters:1]> is bound to a different event loop

**To Reproduce**
occurs in all workflow

**Expected behavior**
when disabled "ComfyUI-Crystools.disable"  everything works again

**Screenshots**
![image](https://github.com/crystian/ComfyUI-Crystools/assets/142649973/87b086a1-34de-46a4-9af9-e519dc8d5165)

**Version:**
Loading: ComfyUI-Manager (V1.25.2)
ComfyUI Revision: 1886 [6a10640f] | Released on '2024-01-08'

**Additional context**
Total VRAM 8191 MB, total RAM 16302 MB
xformers version: 0.0.23.post1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.2+cu118

**Comment by crystian** [comment]
@dcondic ok, I will check, but for now, can you try to disable the monitors on settings? I like to know if it is working
thanks!

**Comment by crystian** [comment]
btw, which version of python do you have?

**Comment by dcondic** [comment]
crystian thanks for answer

With monitors enabled same error happend
![image](https://github.com/crystian/ComfyUI-Crystools/assets/142649973/21c52bab-321e-49e4-b2b3-2fc272e4f93d)
![image](https://github.com/crystian/ComfyUI-Crystools/assets/142649973/9d89ac21-633e-4d9d-a3a5-e1ad60ec4fb2)

as you suggested:
With monitors disabled everything works fine
![image](https://github.com/crystian/ComfyUI-Crystools/assets/142649973/775ad5ed-bd98-49d6-a9a2-f33156e0b0a5)

Python ver.
![image](https://github.com/crystian/ComfyUI-Crystools/assets/142649973/fcdf8cbc-c2bc-4ced-8e67-c573362c7a52)

**Comment by ada-lovecraft** [comment]
Adding to this:
```
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\dev-tools\stable-diffusion\Comfy-UI\main.py", line 241, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "C:\ProgramData\anaconda3\envs\comfy\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\dev-tools\stable-diffusion\Comfy-UI\main.py", line 143, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "D:\dev-tools\stable-diffusion\Comfy-UI\server.py", line 624, in publish_loop
    await self.send(*msg)
  File "D:\dev-tools\stable-diffusion\Comfy-UI\server.py", line 559, in send
    await self.send_json(event, data, sid)
  File "D:\dev-tools\stable-diffusion\Comfy-UI\server.py", line 612, in send_json
    await send_socket_catch_exception(self.sockets[sid].send_json, message)
  File "D:\dev-tools\stable-diffusion\Comfy-UI\server.py", line 40, in send_socket_catch_exception
    await function(message)
  File "C:\ProgramData\anaconda3\envs\comfy\Lib\site-packages\aiohttp\web_ws.py", line 352, in send_json
    await self.send_str(dumps(data), compress=compress)
  File "C:\ProgramData\anaconda3\envs\comfy\Lib\site-packages\aiohttp\web_ws.py", line 336, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "C:\ProgramData\anaconda3\envs\comfy\Lib\site-packages\aiohttp\http_websocket.py", line 729, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\ProgramData\anaconda3\envs\comfy\Lib\site-packages\aiohttp\http_websocket.py", line 644, in _send_frame
    message = await compressobj.compress(message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\comfy\Lib\site-packages\aiohttp\compression_utils.py", line 71, in compress
    async with self._compress_lock:
  File "C:\ProgramData\anaconda3\envs\comfy\Lib\asyncio\locks.py", line 15, in __aenter__
    await self.acquire()
  File "C:\ProgramData\anaconda3\envs\comfy\Lib\asyncio\locks.py", line 106, in acquire
    fut = self._get_loop().create_future()
          ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\comfy\Lib\asyncio\mixins.py", line 20, in _get_loop
    raise RuntimeError(f'{self!r} is bound to a different event loop')
RuntimeError: <asyncio.locks.Lock object at 0x00000160D0C32550 [unlocked, waiters:1]> is bound to a different event loop```
![workflow (1)](https://github.com/crystian/ComfyUI-Crystools/assets/3170885/37688b02-3f7e-4cff-a202-5b0e147a737c)

Python 3.11

**Comment by crystian** [comment]
Remotely? Can you explain it to me, please? Because I think the reason can come from there
Thanks!

**Comment by crystian** [comment]
I didn't test with colab or others ¯\_(ツ)_/¯

**Comment by ada-lovecraft** [comment]
It's running on my pc on my local network. Happens when I sit at the computer and use the same workflow, lol. It's not running in a cloud environment or anything.

**Comment by crystian** [comment]
@ada-lovecraft Oh, ok hehe, I'll check right now, meantime you can deactivate the monitors from the settings

**Comment by crystian** [comment]
btw, I tried it on colab and works! :)

**Comment by crystian** [comment]
can you help me with this?

https://www.reddit.com/r/comfyui/comments/19190qe/comment/kgzv2nx/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by crystian** [comment]
Could you test it? @ada-lovecraft @dcondic on dev

**Comment by LuckyFan** [comment]
Hi @crystian 
I tested your dev branch, it still happens, but not causing Comfyui to quit anymore like before
<img width="552" alt="image" src="https://github.com/crystian/ComfyUI-Crystools/assets/4580969/cee5af34-7688-4489-baa8-9256d90b2c5a">

**Comment by crystian** [comment]
@LuckyFan thanks! I release that and still working on it

**Comment by crystian** [comment]
I tried different scenarios, and I can't reproduce it :(

May you reinstall all dependencies again (removing venv folder)

You can use something like my [gist](https://gist.github.com/crystian/1ffd2e4d97433b419bf5b0f5acf4101a) to install ComfyUI with some extensions in less than 10 minutes

**Comment by crystian** [comment]
the same for you @dcondic and @ada-lovecraft , thanks

**Comment by snottyone** [comment]
i got the same error, comfyui dies in the background
first sign is that the graphs stop working (except the progress bar)
or comfyui just crashes without that happening first
happens so often (as in: every ~5th runs) that i removed the whole package for now

**Comment by crystian** [comment]
I need more info @snottyone please, copy, paste and refill:

---

**Describe the bug**  
A clear and concise description of what the bug is.

**To Reproduce**  
__Please attach a workflow file to make it easier for others to reproduce the error!__

**Expected behavior**  
A clear and concise description of what you expected to happen.

**Screenshots**  
If applicable, add screenshots to help explain your problem.

**Error in console:**  
If applicable, add the error message from the console.

**Versions:**  
Copy the output of the console (4 parts), like this:
```
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
```
```
Total VRAM 12287 MB, total RAM 130996 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
```
```
### Loading: ComfyUI-Manager (V1.25.3)
### ComfyUI Revision: 1886 [6a10640f] | Released on '2024-01-08'
```
```
[Crystools INFO] Crystools version: 1.3.2
[Crystools INFO] NVIDIA Driver detected - 546.33
```

**Additional context**  
Add any other context about the problem here.

**Comment by snottyone** [comment]
> I made a change, it (may) will fix this issue, it is on dev; if you want to try it, you need to do:

for me, fixed it, thank you very much :)

**Comment by crystian** [comment]
just for the check, on dev? @snottyone

**Comment by ada-lovecraft** [comment]
@crystian I'll install the latest dev version and give it a try.

**Comment by snottyone** [comment]
> just for the check, on dev? @snottyone

yes, followed your instructions, dev works like  charm

**Comment by crystian** [comment]
Merge! You can install it normally; thanks for your help! @snottyone
