### ISSUE TITLE
Under the new UI interface, the display of your plugin status occupies too much space. Are there any other solutions to solve this problem?

### ISSUE THREAD

**Issue by wibur0620** [crystian/ComfyUI-Crystools#70]
![image](https://github.com/crystian/ComfyUI-Crystools/assets/131615326/77286be1-1fe6-4c29-88c7-a6e5df592abe)
Could we change the status display to circular icons with a pie chart inside showing the percentage?

**Comment by crystian** [comment]
Sorry, but how can you change the UI? @wibur0620

**Comment by crystian** [comment]
I saw, but, it is beta, so when they will release I'll try to adjust it
