### ISSUE TITLE
Adapt to new UI

### ISSUE THREAD

**Issue by 807502278** [crystian/ComfyUI-Crystools#71]
![ATJR FSX3E9 0MY5VU1C 47](https://github.com/crystian/ComfyUI-Crystools/assets/46019416/252e6aa3-4aa4-46cc-9c7c-a80f099ed032)
Can it be adapted to the new UI?

**Comment by crystian** [comment]
I'll do when it will be more stable

**Comment by Maxadox** [comment]
> ![ATJR FSX3E9 0MY5VU1C 47](https://private-user-images.githubusercontent.com/46019416/344890282-252e6aa3-4aa4-46cc-9c7c-a80f099ed032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzg4NzcsIm5iZiI6MTcyMzAzODU3NywicGF0aCI6Ii80NjAxOTQxNi8zNDQ4OTAyODItMjUyZTZhYTMtNGFhNC00NmNjLTljN2MtYTgwZjA5OWVkMDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDEzNDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNTNlOTk4YmRiNWJjMjQxNmJmYzBjZTkxYjc5MDFkZDdmMjEzODYzMmNkMTc0MzQzOWIwYjgzM2RiNzdiM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.06wJQM40S-4_ja-evD_23UXhFbGrXidnX6lQaFCHT-A) Can it be adapted to the new UI?

How can I get to even display it like that? after I enable the new UI, my monitor is gone :(

**Comment by 807502278** [comment]
> I'll do when it will be more stable

ComfyUI has updated with a new UI. Can it be updated now?

**Comment by kakachiex2** [comment]
Something like chainner would be nice
![Screenshot 2024-08-16 121545](https://github.com/user-attachments/assets/1718d49d-a42e-463e-80e6-3d658087e0c1)

**Comment by crystian** [comment]
I will do this weekend ;)

**Comment by ytoaa** [comment]
I'm holding my breath and waiting.

**Comment by AlexData-Hawkhill** [comment]
yes, looking forward to having your progress-bars show up on the new menu! Nice work so far, Crystian!

**PS: Tiny question:** At the same time I wonder, would it be possible to make a "node" that displays the same live progress-bar-info? So that we could just add a node in the project, and display the same progress-bars inside a node? Is that even possible?

**Comment by chnisar515** [comment]
> > ![ATJR FSX3E9 0MY5VU1C 47](https://private-user-images.githubusercontent.com/46019416/344890282-252e6aa3-4aa4-46cc-9c7c-a80f099ed032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzg4NzcsIm5iZiI6MTcyMzAzODU3NywicGF0aCI6Ii80NjAxOTQxNi8zNDQ4OTAyODItMjUyZTZhYTMtNGFhNC00NmNjLTljN2MtYTgwZjA5OWVkMDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDEzNDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNTNlOTk4YmRiNWJjMjQxNmJmYzBjZTkxYjc5MDFkZDdmMjEzODYzMmNkMTc0MzQzOWIwYjgzM2RiNzdiM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.06wJQM40S-4_ja-evD_23UXhFbGrXidnX6lQaFCHT-A) Can it be adapted to the new UI?
> 
> How can I get to even display it like that? after I enable the new UI, my monitor is gone :(

i am getting same issue.

**Comment by crystian** [comment]
I'm working on that ;)

**Comment by gonzalu** [comment]
On an old install of ComfyUI, I updated to latest versions via Manage Update All and it works... 

![image](https://github.com/user-attachments/assets/95ac8c84-7410-4f27-9ae7-27f409acc8dc)


But like in my production ComfyUI portable install, it will likely stop working for some reason. 

Not sure if this helps or hurts :(

**Comment by Orenji-Tangerine** [comment]
I just did a fresh installation of ComfyUI for a separate environment, I dont see the resource monitor... However on my older set of ComfyUI environment, I did see the resource monitor in the new frontend. Any setting for that?

**Comment by gonzalu** [comment]
> I just did a fresh installation of ComfyUI for a separate environment, I dont see the resource monitor... However on my older set of ComfyUI environment, I did see the resource monitor in the new frontend. Any setting for that?

That's the problem some of us have. It will work for a little bit and then suddenly it will stop working.

**Comment by ZeroCool22** [comment]
Installing this monitor make generations slow?

**Comment by gonzalu** [comment]
> Installing this monitor make generations slow?

no

**Comment by Lalimec** [comment]
did it get fixed, i dont see any monitors on the new ui?
![image](https://github.com/user-attachments/assets/9828bd53-f9c8-4930-a461-24b180a19f3e)

**Comment by gonzalu** [comment]
> did it get fixed, i dont see any monitors on the new ui? ![image](https://private-user-images.githubusercontent.com/65521426/367743087-9828bd53-f9c8-4930-a461-24b180a19f3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDA3MDQsIm5iZiI6MTcyNjUwMDQwNCwicGF0aCI6Ii82NTUyMTQyNi8zNjc3NDMwODctOTgyOGJkNTMtZjljOC00OTMwLWE0NjEtMjRiMTgwYTE5ZjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE1MjY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NDdlZTgzYzI2MmY4ZmFjNGUwNjRmNDNiYzU0ZjViYzRhMjA4NzMxZDkxNGZhOTIyMTFmOTVjMTRiYWQwYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W6E8K-6pTPQZxnOCwgqSOAnZHGubGWOT4idoc6LCqgI)

not yet

**Comment by crystian** [comment]
WIP

**Comment by camoody1** [comment]
All of a sudden today, my progress monitors are missing and my workflow went from 3 to 4 seconds/step to 15 to 20 seconds/step on my RTX 4070Ti. I've changed nothing other than running Update All from within Comfy Manager. I see your nodes were updated yesterday. Have you heard any other complaints about this most recent update?

**Comment by crystian** [comment]
> All of a sudden today, my progress monitors are missing and my workflow went from 3 to 4 seconds/step to 15 to 20 seconds/step on my RTX 4070Ti. I've changed nothing other than running Update All from within Comfy Manager. I see your nodes were updated yesterday. Have you heard any other complaints about this most recent update?

update all your comfy (or reinstall)

**Comment by crystian** [comment]
finally we have the first version, on these days I'll fix some known issues, use F5 ;)

**Comment by Orenji-Tangerine** [comment]
How do I adjust the height or the size of this?
![image](https://github.com/user-attachments/assets/d32e7fe8-ec5a-4922-8dfa-60740e0d27ec)

**Comment by crystian** [comment]
The height nope for now, remember you can remove monitors from settings

**Comment by gonzalu** [comment]
![image](https://github.com/user-attachments/assets/892914e8-0bf0-4f74-9c01-ffb4e3181456)

**Comment by gonzalu** [comment]
I am now getting the progress bar taking up the whole screen vertically... just FYI... 

![image](https://github.com/user-attachments/assets/c4045240-9868-409f-bb3b-7456ada09c0e)

**Comment by gonzalu** [comment]
Only the progress bar does this it seems so far...

**Comment by crystian** [comment]
wt.... hahaha sorry, please update @gonzalu

**Comment by DrJKL** [comment]
> How do I adjust the height or the size of this?
> ![image](https://github.com/user-attachments/assets/d32e7fe8-ec5a-4922-8dfa-60740e0d27ec)
> 

You could add some custom CSS, or maybe a feature request in the comfy frontend repo?

**Comment by crystian** [comment]
umm, if you resize the windows may it adjust "automatically" , please try it, and in settings I added several configurations, even the size of monitors, please check it

**Comment by camoody1** [comment]
@crystian I like where you're headed with the new UI changes. The ability to resize the bars is perfect. Thank you.

I think the next aspect you need to iterate on is the position and size of the Progress bar. I love having the progress bar down there, but as it is currently, the bar fills up the entire Manager bar and covers all of your gauges. I think, perhaps, a better option would be for the Progress Bar to run underneath your other gauges instead of covering them. Or, optionally, give the user the option to reduce its thickness and slide its position up or down inside the Manager bar.

**Comment by crystian** [comment]
> > How do I adjust the height or the size of this?
> > ![image](https://private-user-images.githubusercontent.com/172998895/369802455-d32e7fe8-ec5a-4922-8dfa-60740e0d27ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzU3NzUsIm5iZiI6MTcyNzE3NTQ3NSwicGF0aCI6Ii8xNzI5OTg4OTUvMzY5ODAyNDU1LWQzMmU3ZmU4LWVjNWEtNDkyMi04ZGZhLTYwNzQwZTBkMjdlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQxMDU3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODk1YTI0ZGZhNTdjNWMwMjhiZTZkYmQ0ZGIwNTZhYzFhMTM0NGVmYjA3ZWNlY2U5MTQ3Yzk5ZGUyMTVkMDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kZ3VY85CZSZeatZpLeLZsFrd5guq_vLN_RCDqkq4BFo)
> 
> You could add some custom CSS, or maybe a feature request in the comfy frontend repo?

try again please

**Comment by crystian** [comment]
> @crystian I like where you're headed with the new UI changes. The ability to resize the bars is perfect. Thank you.
> 
> I think the next aspect you need to iterate on is the position and size of the Progress Bar. I love having the progress bar down there, but as it is currently, the bar fills up the entire Manager bar and covers all of your gauges. A better option would be for the Progress Bar to run underneath your other gauges instead of covering them. Or, optionally, give the user the option to choose its thickness and slide its position up or down inside the Manager bar.
> 
> Thank you for your excellent work!

let me check, but I think, it will waste of space if you have a few monitors ...

**Comment by gonzalu** [comment]
Hey @crystian thank you for this... I love the new look for the toolbar mode. 

Can I ask for a free height setting? I need to go lower than 16. Right now the height is messing with the default compact mode

note how the toolbar grows in size at the default 16 px height. 
Thanks if you can do it ;) 

![image](https://github.com/user-attachments/assets/c02b6dff-a097-4385-9b14-d8d6d31764d6)


![image](https://github.com/user-attachments/assets/512885cb-d7d5-4b18-b3ee-0303b5b497d2)

**Comment by crystian** [comment]
update and try again @gonzalu 
I fixed some issues

**Comment by gonzalu** [comment]
> update and try again @gonzalu I fixed some issues

Like a charm... you rock

![image](https://github.com/user-attachments/assets/9b4cfd2d-2d99-4b3f-8657-d1372a36f66e)

**Comment by LukeG89** [comment]
@crystian Why is it no longer in the center? My ADHD liked it more! 😆 

However, I think you need to be prepared for the upcoming 1.2.65 version of the frontend... I've seen MANY changes!😅

**Comment by crystian** [comment]
Omg!

**Comment by gonzalu** [comment]
> @crystian Why is it no longer in the center? My OCD liked it more! 😆
> 
> However, I think you need to be prepared for the upcoming 1.2.65 version of the frontend... I've seen MANY changes!😅

Could they have waited a few months or a few years before making MANY MAJOR changes to the freshly new frontend? LOL

**Comment by crystian** [comment]
I saw that, and I'm crying ... haha @gonzalu @LukeG89
