### ISSUE TITLE
The webui can be used for a period of time and then no response

### ISSUE THREAD

**Issue by LeeKIngKIng** [crystian/ComfyUI-Crystools#74]
**Describe the bug**  
The webUI can run normally for a period of time. Maybe one hour, maybe two...But finally it will be no response.
However, the http request works and the terminal can still prints out the logging info，so I realize that the problem is on the socket. 
As we know, [Crystools](https://github.com/crystian/ComfyUI-Crystools) will send msgs continuously. So I try to disable it and that helps. But I don't know the deep reason.
By the way，I also run the webUI in the iframe on other website and there’s going to be a situation like multiple user. 

**Versions:**  
```
** Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
```
```
Total VRAM 22516 MB, total RAM 176330 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM

```
```
[Crystools INFO] Crystools version: 1.12.0
[Crystools INFO] CPU: Intel(R) Xeon(R) Platinum 8372HC CPU @ 3.40GHz - Arch: x86_64 - OS: Linux 5.4.0-186-generic
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA A10
[Crystools INFO] 1) NVIDIA A10
[Crystools INFO] 2) NVIDIA A10
[Crystools INFO] 3) NVIDIA A10
[Crystools INFO] NVIDIA Driver: 535.171.04
```
```
### Loading: ComfyUI-Manager (V2.30.1)
### ComfyUI Revision: 2258 [746a0410] | Released on '2024-06-16'
```

**Comment by crystian** [comment]
I tried it but I could not reproduce.

I see you have old version of several componentes, please update comfy-ui and crystools with latest versions (I recomend yout to do a backup before, just in case).

Reopen this issue with new information please, thanks!
