### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Enchante503** [crystian/ComfyUI-Crystools#75]
Cannot import /home/enchante/diffusion/ComfyUI/custom_nodes/ComfyUI-Crystools module for custom nodes: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte

**Comment by crystian** [comment]
Pleas try to install the dependencies manually 

https://github.com/crystian/ComfyUI-Crystools#install-from-github

if it does not work, create an issue using the form format please
