### ISSUE TITLE
Can the resource monitor provide a graph over time

### ISSUE THREAD

**Issue by linksluckytime** [crystian/ComfyUI-Crystools#83]
Hi there,

First of all, I want to say that "Crystools" has become an indispensable tool for me. I absolutely love its resource monitoring and pipeline features. This time, I’d like to share some suggestions about the resource monitoring feature.

When testing hardware or different software versions, I often want to know the resource usage over a period of time. However, currently, I can only observe short-term changes through "Crystools" or the "Task Manager". 

While training models, I discovered "TensorBoard", and I think it would be really useful if "Crystools" could provide resource usage curves as well. This would make "Crystools" beneficial in even more scenarios.

Sorry if my English isn’t very good. The above content was generated using a translation tool, so I apologize for any potential inaccuracies. Once again, thank you for providing "Crystools".

Best regards.

**Comment by crystian** [comment]
Hi, and thanks for your words!
I like it! but i tried to do something similar but, it's complicate to do and I don't have time :(

**Comment by Ainaemaet** [comment]
I'm fairly new to all of this but AI has been a huge help, I will see what I can do - as this would be absolutely wonderful to have.
