### ISSUE TITLE
子路径问题，麻烦研究一下

### ISSUE THREAD

**Issue by GitHub4LP** [crystian/ComfyUI-Crystools#87]
**Describe the bug**  
https://aistudio.baidu.com/projectdetail/8064463
注意安装依赖
`~/work/venv/bin/python3 -m pip install -r ~/work/ComfyUI/custom_nodes/ComfyUI-Crystools/requirements.txt`
load js failed

**To Reproduce**  
__Please attach a workflow file to make it easier for others to reproduce the error!__

**Expected behavior**  

**Screenshots**  

**Error in console:**  
If applicable, add the error message from the console.

**Versions:**  
Copy the output of the console (4 parts), like this:
```
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
```
```
Total VRAM 12287 MB, total RAM 130996 MB
Set vram state to: NORMAL_VRAM
```
```
[Crystools INFO] Crystools version: 1.9.2
[Crystools INFO] CPU: AMD Ryzen 9 5950X 16-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3080 Ti
[Crystools INFO] NVIDIA Driver: 546.33
```
```
### Loading: ComfyUI-Manager (V1.25.3)
### ComfyUI Revision: 1886 [6a10640f] | Released on '2024-01-08'
```

**Additional context**

**Comment by crystian** [comment]
what is the issue? please in english!
update your versions, are so old!
