### ISSUE TITLE
Consistent Comfy Crash

### ISSUE THREAD

**Issue by CaptainGrock** [crystian/ComfyUI-Crystools#9]
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Happens when I run a workflow against multiple models in a workflow (attaching sample JSON CrysCrash)
[CrysCrash.txt](https://github.com/crystian/ComfyUI-Crystools/files/13875883/CrysCrash.txt)
 
Other than the error message, there isn't any other indicator that there are rendering issues (and I haven't experienced this crash prior to using the node)

**Comment by crystian** [comment]
hi, I think, it could be the scenario, do you use "http://127.0.0.1:8188"? because firewalls or other protections can blocked it
I tried it and works the load (not try the queue).
I close this issue and fill a new one with "bug report" with more data, thanks!

**Comment by CaptainGrock** [comment]
Hi there,

yes I use  "http://127.0.0.1:8188/" and the monitoring works most of the
time but with this particular workflow where I'm switching models, it's
crashed a few times so far (so there's some consistency). Noting that the
crash happens most of the way through execution (so it's not just at the
beginning).

Any other thoughts?

**Comment by crystian** [comment]
ah okey, I made a change for next release (may be today) so, you can try it again 🤞 , I'll write here when it happens
Thanks!

**Comment by crystian** [comment]
@CaptainGrock released, can you check it?

**Comment by CaptainGrock** [comment]
Thanks - will continue testing but so far so good
