### ISSUE TITLE
The request path is incorrect

### ISSUE THREAD

**Issue by GitHub4LP** [crystian/ComfyUI-Crystools#90]
**Describe the bug**  
The request path is incorrect

**Screenshots**  
![屏幕截图 2024-07-30 190930](https://github.com/user-attachments/assets/b148f122-6f96-440e-9750-224c586e8b8e)
![屏幕截图 2024-07-30 191438](https://github.com/user-attachments/assets/6029bba6-6ef3-408c-ad9e-5fbdb2517160)

**Comment by crystian** [comment]
Please fill the bug report https://github.com/crystian/ComfyUI-Crystools/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by GitHub4LP** [comment]
**Versions:**  
Copy the output of the console (4 parts), like this:
```
** Platform: Linux
** Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
```
```
Total VRAM 14931 MB, total RAM 385607 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
Using xformers cross attention
```
```
[Crystools INFO] Crystools version: 1.15.1
[Crystools INFO] CPU: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz - Arch: x86_64 - OS: Linux 4.4.0-142-generic
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) Tesla T4
[Crystools INFO] NVIDIA Driver: 535.129.03
```
```
### Loading: ComfyUI-Manager (V2.48.2)
### ComfyUI Revision: 2418 [66d35c07] | Released on '2024-07-29'
```
