### ISSUE TITLE
incorrect paths

### ISSUE THREAD

**Issue by GitHub4LP** [crystian/ComfyUI-Crystools#91]
**Describe the bug**  
I'm running ComfyUI on a subpath, with port forwarding via code-server. ComfyUI is running well, and it loads your plugin's JavaScript files correctly. However, your JavaScript references to ComfyUI's `api.js`, `app.js`, `widgets.js`, etc., do not include the subpath and are directly requesting them under the domain name, which leads to incorrect paths and errors.

**Screenshots**  
![屏幕截图 2024-07-30 190930](https://github.com/user-attachments/assets/b148f122-6f96-440e-9750-224c586e8b8e)
![屏幕截图 2024-07-30 191438](https://github.com/user-attachments/assets/6029bba6-6ef3-408c-ad9e-5fbdb2517160)

**Comment by crystian** [comment]
versions please!
and I don't support tunnes or whatever baidu is

**Comment by GitHub4LP** [comment]
Thank you for your response.
This is not related to Baidu; Paperspace is the same. As I described above, the main issue is adapting to the subpath.

**Comment by crystian** [comment]
as I said before, I need to see versions as the form to create an issue said, please!
yes this is realte to baidu/tunnel, because it works with localhost

**Comment by GitHub4LP** [comment]
[versions ](https://github.com/crystian/ComfyUI-Crystools/issues/90#issuecomment-2258589956)

**Comment by crystian** [comment]
sorry but I can't reproduce it, if you want you can create a PR

**Comment by GitHub4LP** [comment]
> sorry but I can't reproduce it, if you want you can create a PR

@crystian 

WSL2
`jupyter lab --no-browser --ip=0.0.0.0 --allow-root --notebook-dir=~ --LabApp.token= --LabApp.allow_origin=* --LabApp.base_url=/jupyter/`
run ComfyUI and request http://127.0.0.1:8888/jupyter/proxy/8188/
